apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: duckdns-cert
  namespace: apn-stack
spec:
  secretName: duckdns-tls
  issuerRef:
    name: letsencrypt-http01
    kind: ClusterIssuer
  dnsNames:
  - rvanaken.duckdns.org