apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: selfsigned-cert
  namespace: apn-stack
spec:
  secretName: selfsigned-tls  # Kubernetes Secret where the cert will be stored
  issuerRef:
    name: selfsigned-cluster-issuer  # Must match the Issuer name
    kind: ClusterIssuer
    group: cert-manager.io
  dnsNames:
  - rvanaken.duckdns.org
  - apn.local