apiVersion: v1
kind: ConfigMap
metadata:
  name: lighttpd-config
  namespace: apn-stack
data:
  index.html: |
{{ .Values.config.indexHtml | indent 4 }}

  99_custom.conf: |
{{ .Values.config.customConf | indent 4 }}
