apiVersion: apps/v1
kind: Deployment
metadata:
  name: lighttpd
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: lighttpd
  template:
    metadata:
      labels:
        app: lighttpd
    spec:
      containers:
        - name: lighttpd
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
              name: http

          startupProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: {{ .Values.probes.startup.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.startup.periodSeconds }}
            failureThreshold: {{ .Values.probes.startup.failureThreshold }}

          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.liveness.periodSeconds }}

          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}

          volumeMounts:
            - name: lighttpd-config
              mountPath: /var/www/html/index.html
              subPath: index.html

            - name: lighttpd-config
              mountPath: /etc/lighttpd/conf-enabled/99_custom.conf
              subPath: 99_custom.conf

      volumes:
        - name: lighttpd-config
          configMap:
            name: lighttpd-config
