apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: "2026-08-12T07:10:23Z"
  labels:
    app.kubernetes.io/name: argocd-cmd-params-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cmd-params-cm
  namespace: argocd
  resourceVersion: "1992"
  uid: 0bfe40fe-9b4f-4873-9d3e-b58073625d57
data:
  server.insecure: "true"
  server.basehref: "/argo"
  server.rootpath: "/argo"
