apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-initdb
  namespace: apn-stack
data:
  seed.js: |
    db = db.getSiblingDB('db');
    db.createCollection('users');
    db.users.insertMany([
      { name: "Roeland", email: "roeland@example.com" }
    ]);