apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-server-tls
  namespace: argocd
spec:
  isCA: true
  commonName: apn-ca
  secretName: argocd-server-tls
  issuerRef:
    name: clusterissuer-selfsigned
    kind: ClusterIssuer
  dnsNames:
  - argocd.local
  
---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: apn-tls
  namespace: apn-stack
spec:
  isCA: true
  commonName: apn-ca
  secretName: apn-tls
  issuerRef:
    name: clusterissuer-selfsigned
    kind: ClusterIssuer
  dnsNames:
  - apn.local

---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: duck-tls
  namespace: apn-stack
spec:
  isCA: true
  commonName: apn-ca
  secretName: duck-tls
  issuerRef:
    name: clusterissuer-selfsigned
    kind: ClusterIssuer
  dnsNames:
  - rvanaken.duckdns.org

---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-tls
  namespace: monitoring
spec:
  isCA: true
  commonName: apn-ca
  secretName: grafana-tls
  issuerRef:
    name: clusterissuer-selfsigned
    kind: ClusterIssuer
  dnsNames:
  - grafana.local

---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: portainer-tls
  namespace: portainer
spec:
  isCA: true
  commonName: apn-ca
  secretName: portainer-tls
  issuerRef:
    name: clusterissuer-selfsigned
    kind: ClusterIssuer
  dnsNames:
  - portainer.local

---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: portainer-tls-signed
  namespace: portainer
spec:
  secretName: portainer-tls
  commonName: portainer.local
  dnsNames:
    - portainer.local
  issuerRef:
    name: portainer-ca-signed
    kind: ClusterIssuer
