lighttpd:
  replicaCount: 1
  image:
    tag: "1.0"

node:
  replicaCount: 1
  image:
    tag: "1.0"
  mongo:
    secretName: mongo-creds

mongo:
  replicaCount: 1
  storage:
    size: 1Gi
  credentials:
    username: admin
    password: admin123
    database: db