apiVersion: apps/v1
kind: Deployment
metadata:
  name: node
  namespace: apn-stack
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
        - name: node
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mongo.secretName }}
                  key: {{ .Values.mongo.usernameKey }}

            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mongo.secretName }}
                  key: {{ .Values.mongo.passwordKey }}

            - name: MONGO_URL
              value: "{{ .Values.mongo.url }}"

          ports:
            - containerPort: 3000
              name: http
