apiVersion: v1
kind: Service
metadata:
  name: node
  namespace: apn-stack
spec:
  type: {{ .Values.service.type }}
  selector:
    app: node
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000

      