apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.mongo.secretName }}
  namespace: apn-stack
type: Opaque
stringData:
  {{ .Values.mongo.usernameKey }}: {{ .Values.credentials.username }}
  {{ .Values.mongo.passwordKey }}: {{ .Values.credentials.password }}
  {{ .Values.mongo.databaseKey }}: {{ .Values.credentials.database }}
